---
title: "Mean_TaskTime"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Skripte/import.R")
source("Skripte/subsets_erstellen.R")
source("Skripte/all_tpt.R")
```

##Durchschnittliche Bearbeitungszeit (bereinigte Daten)
### Nach Aufgabe 
```{r}
plot(mean_tpt,type= "l", main = "Durschnittliche Dauer der Aufgaben", ylab= "Zeit in Millisekunden", xlab = "Aufgaben")
plot(mean_tptr,type= "l", main = "Durschnittliche Dauer der Aufgaben", ylab= "Zeit in Sekunden", xlab = "Aufgaben")
```
### Nach Geschlechtern
```{r}
#Millisekunden
plot(mean_tpt_f,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Geschlechtern", ylab= "Zeit in Millisekunden", xlab = "Aufgaben")
lines(mean_tpt_m, type= "l", col = "blue")
#Sekunden
plot(mean_tptr_f,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Geschlechtern", ylab= "Zeit in Sekunden", xlab = "Aufgaben")
lines(mean_tptr_m, type= "l", col = "blue")
```
### Nach Altersgruppe
```{r}
#Millisekunden
plot(mean_tpt_1120,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Altersgruppen", ylab= "Zeit in Millisekunden", xlab = "Aufgaben")
lines(mean_tpt_2130, type= "l", col = "green")
lines(mean_tpt_3140, type= "l", col = "red")
lines(mean_tpt_4150, type= "l", col = "yellow")
lines(mean_tpt_5160, type= "l", col = "orange")
lines(mean_tpt_60, type= "l", col = "grey")
#Sekunden
plot(mean_tptr_1120,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Altersgruppen", ylab= "Zeit in Sekunden", xlab = "Aufgaben")
lines(mean_tptr_2130, type= "l", col = "green")
lines(mean_tptr_3140, type= "l", col = "red")
lines(mean_tptr_4150, type= "l", col = "yellow")
lines(mean_tptr_5160, type= "l", col = "orange")
lines(mean_tptr_60, type= "l", col = "blue")

```

### Nach Betriebssystem
```{r}
#Millisekunden
plot(mean_tpt_iOS,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Betriebssystem", ylab= "Zeit in Millisekunden", xlab = "Aufgaben")
lines(mean_tpt_Android, type= "l", col = "blue")
#Sekunden
plot(mean_tptr_iOS,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Betriebssystem", ylab= "Zeit in Sekunden", xlab = "Aufgaben")
lines(mean_tptr_Android, type= "l", col = "blue")
```

### Nach Smartphone Nutzung
```{r}
#Millisekunden
plot(mean_tpt_mt,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Smartphone Nutzung", ylab= "Zeit in Millisekunden", xlab = "Aufgaben", ylim=c(1500,5100))
lines(mean_tpt_t, type= "l", col = "blue")
#lines(mean_tpt_mw, type= "l", col = "rot")
#Sekunden
plot(mean_tptr_mt,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Smartphone Nutzung", ylab= "Zeit in Sekunden", xlab = "Aufgaben", ylim=c(1.5,5.1))
lines(mean_tptr_t, type= "l", col = "blue")
#lines(mean_tptr_mw, type= "l", col = "rot")
```

### Nach Smartphone Erfahrung
```{r}
#Millisekunden
plot(mean_tpt_ss,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Smartphone  Erfahrung", ylab= "Zeit in Millisekunden", xlab = "Aufgaben", ylim=c(1500,5100))
lines(mean_tpt_s, type= "l", col = "blue")
lines(mean_tpt_m, type= "l", col = "red")
lines(mean_tpt_u, type= "l", col = "yellow")
lines(mean_tpt_su, type= "l", col = "green")
#Sekunden
plot(mean_tptr_ss,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Smartphone Erfahrung", ylab= "Zeit in Sekunden", xlab = "Aufgaben", ylim=c(1.5,5.1))
lines(mean_tptr_s, type= "l", col = "blue")
lines(mean_tptr_m, type= "l", col = "red")
lines(mean_tptr_u, type= "l", col = "yellow")
lines(mean_tptr_su, type= "l", col = "green")
```

### Nach Uhrzeit
```{r}
#Millisekunden
plot(mean_tpt_mo,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Uhrzeit", ylab= "Zeit in Millisekunden", xlab = "Aufgaben", ylim=c(1500,5100))
lines(mean_tpt_a, type= "l", col = "blue")
lines(mean_tpt_n, type= "l", col = "red")
lines(mean_tpt_e, type= "l", col = "yellow")
#Sekunden
plot(mean_tptr_mo,type= "l", main = "Durschnittliche Dauer der Aufgaben nach Uhrzeit", ylab= "Zeit in Sekunden", xlab = "Aufgaben", ylim=c(1.5,5.1))
lines(mean_tptr_a, type= "l", col = "blue")
lines(mean_tptr_n, type= "l", col = "red")
lines(mean_tptr_e, type= "l", col = "yellow")
```