---
title: "Plots"
output: html_document
---
# Grunddaten
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Skripte/import.R")
source("Skripte/subsets_erstellen.R")
source("Skripte/all_tpt.R")
```

## Geschlechterverteilung
```{r}
plot(data$Geschlecht, main = "Biologisches Geschlecht", ylab= "Anzahl Personen", ylim=c(0,100))
plot(data_ishiharaclean$Geschlecht, main = "Biologisches Geschlecht ohne Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,100))
plot(data_ishiharafalse$Geschlecht, main = "Biologisches Geschlecht mit Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,25))
```

## Altersverteilung 

```{r}
plot(data$Alter, main = "Alter", ylab= "Anzahl Personen", ylim=c(0,75))
plot(data_ishiharaclean$Alter, main = "Alter ohne Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,60))
plot(data_ishiharafalse$Alter, main = "Alter mit Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,15))
```

## Verteilung der Nutzung des Betriebssystems
```{r}
plot(data$OS, main = "Betriebssystem", ylab= "Anzahl Personen", ylim=c(0,80))
plot(data_ishiharaclean$OS, main = "Betriebssystem bereinigt", ylab= "Anzahl Personen", ylim=c(0,80))
plot(data_ishiharafalse$OS, main = "Betriebssystem mit Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,15))
```

## Smartphone Nutzung
```{r}
plot(data$'Smartphone Nutzung', main = "Smartphone Nutzungshäufigkeit", ylab= "Anzahl Personen", ylim=c(0,110))
plot(data_ishiharaclean$'Smartphone Nutzung', main = "Smartphone Nutzungshäufigkeit bereinigt", ylab= "Anzahl Personen", ylim=c(0,110))
plot(data_ishiharafalse$'Smartphone Nutzung', main = "Smartphone Nutzungshäufigkeit mit Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,20))
```

## Smartphone Nutzungserfahrung
```{r}
plot(data$'Smartphone Nutzungserfahrung', main = "Smartphone Nutzungserfahrung", ylab= "Anzahl Personen", ylim=c(0,70))
plot(data_ishiharaclean$'Smartphone Nutzungserfahrung', main = "Smartphone Nutzungserfahrung bereinigt", ylab= "Anzahl Personen", ylim=c(0,70))
plot(data_ishiharafalse$'Smartphone Nutzungserfahrung', main = "Smartphone Nutzungserfahrung mit Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,15))
```
## Smartphone Nutzungserfahrung
```{r}
plot(data$'Smartphone Nutzungserfahrung', main = "Smartphone Nutzungserfahrung", ylab= "Anzahl Personen", ylim=c(0,70))
plot(data_ishiharaclean$'Smartphone Nutzungserfahrung', main = "Smartphone Nutzungserfahrung bereinigt", ylab= "Anzahl Personen", ylim=c(0,70))
plot(data_ishiharafalse$'Smartphone Nutzungserfahrung', main = "Smartphone Nutzungserfahrung mit Farbfehlsichtigkeit", ylab= "Anzahl Personen", ylim=c(0,15))
```
