---
title: "Univariante Analyse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Geschlecht
Summary:
```{r}
summary(data$Geschlecht)
```
Plot:

```{r pressure, echo=FALSE}
plot(data$Geschlecht, main = "Biologisches Geschlecht", ylab= "Anzahl Personen")
```

##Alter
###Summary:
```{r pressure, echo=FALSE}
summary(Test_data1$Alter)
```

###Plot:

```{r pressure, echo=FALSE}
plot(Test_data1$Alter, main = "Alter", ylab= "Anzahl Personen")
```

##Smartphone Nutzung
###Summary:
```{r pressure, echo=FALSE}
summary(Test_data1$`Smartphone Nutzung`)
```

###Plot:

```{r pressure, echo=FALSE}
plot(Test_data1$`Smartphone Nutzung`,  main = "Häufigkeit der Smartphonenutzung", ylab= "Anzahl Personen")
```
##Smartphone Nutzungserfahrung
###Summary:
```{r}
summary(Test_data1$`Smartphone Nutzungserfahrung`)
```

###Plot:

```{r pressure, echo=FALSE}
plot(Test_data1$`Smartphone Nutzungserfahrung`, main = "Häufigkeit der Smartphone-Erfahrung", ylab= "Anzahl Personen")
```
##Seh-Schwäche
###Summary:
Frage? Wie die Zahlen am besten in Faktoren umwandeln
```{r}
summary(Test_data1$`Rot-Grün-Sehschwäche`)
```

###Plot:

```{r pressure, echo=FALSE}
plot(Test_data1$`Rot-Grün-Sehschwäche`,type= "l", main = "Rot-Grün-Schwäche", ylab= "Ausprägung", xlab = "Versuchsteilnehmer")
```

##Zeit Gesamt
###Summary:
```{r}
summary(Test_data1$`Zeit gesamt`)
```

###Plot:

```{r pressure, echo=FALSE}
plot(Test_data1$`Zeit gesamt`,type= "l",main="Dauer Aufgabe 1", ylab= "Zeit in Sekunden", xlab = "Versuchsteilnehmer")
```

##Richtig
###Summary:
```{r}
summary(Test_data1$Richtig)
```

###Plot:

```{r pressure, echo=FALSE}
plot(Test_data1$Richtig, type= "l", main="Richtige Aufgaben", ylab= "Anzahl", xlab = "Versuchsteilnehmer")
```

##Falsch
###Summary:
```{r}
summary(Test_data1$FALSCH)
```

###Plot:

```{r pressure, echo=FALSE}
plot(Test_data1$FALSCH,type= "l", main="Falsche Aufgaben", ylab= "Anzahl falsche Aufgabe", xlab = "Versuchsteilnehmer")
```

```{r pressure, echo=FALSE}
plot(Test_data1$Richtig, type= "l", col = "green", main="Richtige und falsche Aufgaben", ylab= "Anzahl", xlab = "Versuchsteilnehmer")
lines(Test_data1$FALSCH, type= "l", col = "red")
```

##Zeit Aufgabe 1 
###Summary:
```{r}
summary(Test_data1$Z1)
```

###Plot:

```{r }
plot(Test_data1$Z1,type= "l")
plot(Test_data1$Z1,type= "l", col = "green", main="Zeit pro Aufgabe n = 1, 25, 50, 75, 100", ylab= "Zeit in Mikrosekunden", xlab = "Versuchsteilnehmer",ylim = c(100, 250))
lines(Test_data1$Z25, type= "l", col = "red")
lines(Test_data1$Z50, type= "l", col = "blue")
lines(Test_data1$Z75, type= "l", col = "yellow")
lines(Test_data1$Z100, type= "l", col = "orange")
```